#!/bin/bash
# install-cicerone.sh - Universal installer for Ubuntu/Debian/RHEL/CentOS
#
# Usage:
#   sudo ./install-cicerone.sh
#
# This script:
#   1. Creates the cicerone user and group
#   2. Creates required directories
#   3. Installs the binary
#   4. Generates an auth token
#   5. Installs and starts the systemd service

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Check if running as root
if [ "$EUID" -ne 0 ]; then
    log_error "Please run as root (use sudo)"
    exit 1
fi

# Detect OS
if [ -f /etc/debian_version ]; then
    OS="debian"
    NOLOGIN_SHELL="/usr/sbin/nologin"
    PKG_MANAGER="apt"
    log_info "Detected: Debian/Ubuntu"
elif [ -f /etc/redhat-release ]; then
    OS="rhel"
    NOLOGIN_SHELL="/sbin/nologin"
    PKG_MANAGER="dnf"
    # Fallback to yum for older RHEL
    if ! command -v dnf &>/dev/null; then
        PKG_MANAGER="yum"
    fi
    log_info "Detected: RHEL/CentOS/Fedora"
else
    log_error "Unsupported OS. This script supports Debian/Ubuntu and RHEL/CentOS/Fedora."
    exit 1
fi

# Check for binary
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
if [ -f "$SCRIPT_DIR/../cicerone" ]; then
    BINARY_PATH="$SCRIPT_DIR/../cicerone"
elif [ -f "./cicerone" ]; then
    BINARY_PATH="./cicerone"
elif [ -f "/usr/local/bin/cicerone" ]; then
    BINARY_PATH="/usr/local/bin/cicerone"
    log_warn "Using existing binary at /usr/local/bin/cicerone"
else
    log_error "Cicerone binary not found. Build it first: go build -o cicerone ."
    exit 1
fi

log_info "Using binary: $BINARY_PATH"

# 1. Create user and group
if ! id cicerone &>/dev/null; then
    useradd --system --no-create-home --shell "$NOLOGIN_SHELL" cicerone
    log_info "Created cicerone user"
else
    log_info "cicerone user already exists"
fi

# 2. Create directories
log_info "Creating directories..."
mkdir -p /etc/cicerone/certs
mkdir -p /var/lib/cicerone
mkdir -p /var/log/cicerone

# 3. Set ownership
chown -R cicerone:cicerone /var/lib/cicerone /var/log/cicerone /etc/cicerone
chmod 750 /var/lib/cicerone /var/log/cicerone
chmod 755 /etc/cicerone
chmod 750 /etc/cicerone/certs

# 4. Install binary
log_info "Installing binary..."
cp "$BINARY_PATH" /usr/local/bin/cicerone
chmod 755 /usr/local/bin/cicerone

# 5. Install systemd service file
log_info "Installing systemd service..."
cat > /etc/systemd/system/cicerone.service << 'EOF'
[Unit]
Description=Cicerone Server - Secure Vault and Task Management
Documentation=https://idm.wezzel.com/crab-meat-repos/cicerone
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=cicerone
Group=cicerone
Environment="CICERONE_HOST=0.0.0.0"
Environment="CICERONE_PORT=5001"
Environment="CICERONE_SECURITY=high"
EnvironmentFile=/etc/cicerone/environment
ExecStart=/usr/local/bin/cicerone serve start \
  --host ${CICERONE_HOST} \
  --port ${CICERONE_PORT} \
  --security ${CICERONE_SECURITY} \
  --token ${CICERONE_TOKEN} \
  --vault-path /var/lib/cicerone/vault.db
Restart=on-failure
RestartSec=5
TimeoutStartSec=30
TimeoutStopSec=10

# Security hardening
NoNewPrivileges=yes
PrivateTmp=yes
ProtectSystem=strict
ProtectHome=yes
ReadWritePaths=/var/lib/cicerone /var/log/cicerone
ReadOnlyPaths=/etc/cicerone

# Resource limits
LimitNOFILE=65536
LimitNPROC=512

[Install]
WantedBy=multi-user.target
EOF

# 6. Generate auth token
log_info "Generating auth token..."
TOKEN=$(openssl rand -base64 32)

# 7. Create environment file
cat > /etc/cicerone/environment << EOF
# Cicerone Server Configuration
# Generated by install-cicerone.sh on $(date -u +"%Y-%m-%d %H:%M:%S UTC")

# Network settings
CICERONE_HOST=0.0.0.0
CICERONE_PORT=5001

# Security level: plain, medium, high, full
CICERONE_SECURITY=high

# Authentication token (KEEP SECRET!)
CICERONE_TOKEN=$TOKEN
EOF

chmod 600 /etc/cicerone/environment
chown cicerone:cicerone /etc/cicerone/environment

# 8. SELinux context (RHEL only)
if [ "$OS" = "rhel" ]; then
    if command -v semanage &>/dev/null; then
        log_info "Configuring SELinux contexts..."
        semanage fcontext -a -t var_lib_t "/var/lib/cicerone(/.*)?" 2>/dev/null || true
        semanage fcontext -a -t etc_t "/etc/cicerone(/.*)?" 2>/dev/null || true
        restorecon -Rv /var/lib/cicerone 2>/dev/null || true
        restorecon -Rv /etc/cicerone 2>/dev/null || true
    fi
    
    # Firewall
    if command -v firewall-cmd &>/dev/null; then
        log_info "Configuring firewall..."
        firewall-cmd --permanent --add-port=5001/tcp 2>/dev/null || true
        firewall-cmd --reload 2>/dev/null || true
    fi
fi

# 9. Reload systemd
log_info "Reloading systemd daemon..."
systemctl daemon-reload

# 10. Enable and start service
log_info "Enabling cicerone service..."
systemctl enable cicerone

log_info "Starting cicerone service..."
systemctl start cicerone

# 11. Check status
sleep 2
if systemctl is-active --quiet cicerone; then
    STATUS="${GREEN}RUNNING${NC}"
else
    STATUS="${RED}FAILED${NC}"
fi

# Output summary
echo ""
echo "=========================================="
echo -e " Cicerone Server ${STATUS}"
echo "=========================================="
echo ""
echo "Auth Token: $TOKEN"
echo ""
echo "⚠️  SAVE THIS TOKEN SECURELY! ⚠️"
echo "   You'll need it for client authentication."
echo ""
echo "Commands:"
echo "  Status:   systemctl status cicerone"
echo "  Logs:     journalctl -u cicerone -f"
echo "  Stop:     systemctl stop cicerone"
echo "  Restart:  systemctl restart cicerone"
echo ""
echo "Client usage:"
echo "  cicerone client connect -s http://localhost:5001 -t YOUR_TOKEN"
echo "  cicerone client vault set my-secret secret \"my-value\" -s http://localhost:5001 -t YOUR_TOKEN"
echo ""